-- Migration generated by the command below; DO NOT EDIT.
-- hydra:generate hydra migrate gen

ALTER TABLE hydra_oauth2_obfuscated_authentication_session DROP FOREIGN KEY hydra_oauth2_obfuscated_authentication_session_nid_fk_idx;
