-- Migration generated by the command below; DO NOT EDIT.
-- hydra:generate hydra migrate gen

ALTER TABLE hydra_oauth2_trusted_jwt_bearer_issuer DROP FOREIGN KEY hydra_oauth2_trusted_jwt_bearer_issuer_nid_fk_idx;
